#include "header.h"

#include <pic32mx.h>
#include <stdint.h>
#include <stdbool.h>

#define EEPROM_SLAVE_ADDR 0x50
#define SEED_ADDR 0xFF
#define HIGHSCORES_ADDR 0x30
#define HIGHSCORE_SIZE 5
#define HIGHSCORES_MAX HIGHSCORE_SIZE * 10 + HIGHSCORE_SIZE

#define EEPROM_WRITE 0
#define EEPROM_READ 1

/* Wait for I2C bus to become idle */
void i2c_idle() {
	while(I2C1CON & 0x1F || I2C1STAT & (1 << 14)); //TRSTAT
}

/* Send one byte on I2C bus, return ack/nack status of transaction */
bool i2c_send(uint8_t data) {
	i2c_idle();
	I2C1TRN = data;
	i2c_idle();
	return !(I2C1STAT & (1 << 15)); //ACKSTAT
}

/* Receive one byte from I2C bus */
uint8_t i2c_recv() {
	i2c_idle();
	I2C1CONSET = 1 << 3; //RCEN = 1
	i2c_idle();
	I2C1STATCLR = 1 << 6; //I2COV = 0
	return I2C1RCV;
}

/* Send acknowledge conditon on the bus */
void i2c_ack() {
	i2c_idle();
	I2C1CONCLR = 1 << 5; //ACKDT = 0
	I2C1CONSET = 1 << 4; //ACKEN = 1
}

/* Send not-acknowledge conditon on the bus */
void i2c_nack() {
	i2c_idle();
	I2C1CONSET = 1 << 5; //ACKDT = 1
	I2C1CONSET = 1 << 4; //ACKEN = 1
}

/* Send start conditon on the bus */
void i2c_start() {
	i2c_idle();
	I2C1CONSET = 1 << 0; //SEN
	i2c_idle();
}

/* Send restart conditon on the bus */
void i2c_restart() {
	i2c_idle();
	I2C1CONSET = 1 << 1; //RSEN
	i2c_idle();
}

/* Send stop conditon on the bus */
void i2c_stop() {
	i2c_idle();
	I2C1CONSET = 1 << 2; //PEN
	i2c_idle();
}

void i2c_control(int address, int rw) {
	do {
		i2c_start();
	} while(!i2c_send((EEPROM_SLAVE_ADDR << 1) | rw));
}

void initEEprom(void) {
	/* Set up i2c */
	I2C1CON = 0x0;
	/* I2C Baud rate should be less than 400 kHz, is generated by dividing
	the 40 MHz peripheral bus clock down */
	I2C1BRG = 0x0C2;
	I2C1STAT = 0x0;
	I2C1CONSET = 1 << 13; //SIDL = 1
	I2C1CONSET = 1 << 15; // ON = 1

    /* uint8_t tmp = 0; */
    /*  */
    /* print(0, "write"); */
    /* i2c_control(EEPROM_SLAVE_ADDR, EEPROM_WRITE); */
    /* print(0, "top addr"); */
    /* while(!i2c_send(0x00)); */
    /* print(0, "bottom addr"); */
    /* while(!i2c_send(0x00)); */
    /* print(0, "read"); */
    /* i2c_control(EEPROM_SLAVE_ADDR, EEPROM_READ); */
    /* print(0, "receive"); */
    /* tmp = i2c_recv(); */
    /* print(0, "nack"); */
    /* i2c_nack(); */
    /* print(0, "stop"); */
    /* i2c_stop(); */
    /* print(0, "done"); */
    /* print(1, itoaconv(tmp)); */

}

void writeEEprom(short address, char data) {
    i2c_control(EEPROM_SLAVE_ADDR, EEPROM_WRITE);
    while(!i2c_send((address & 0xFF00) >> 8));
    while(!i2c_send(address & 0xFF));
    while(!i2c_send(data));
    i2c_stop();
}

char* readEEpromBytes(short address, int n_bytes) {
    char data[n_bytes-1];

    i2c_control(EEPROM_SLAVE_ADDR, EEPROM_WRITE);
    while(!i2c_send((address & 0xFF00) >> 8));
    while(!i2c_send(address & 0xFF));

    i2c_control(EEPROM_SLAVE_ADDR, EEPROM_READ);
    for(int i = 0; i < n_bytes; i++) {
        data[i] = i2c_recv();
        if(i < n_bytes-1)
            i2c_ack();
    }
    i2c_nack();
    i2c_stop();

    return data;
}

void newHighscore(char name[4], char new_score) {
    char* highScores = readEEpromBytes(HIGHSCORES_ADDR, HIGHSCORES_MAX);
    char lowest_score = new_score;
    char lowest_index = -1;

    for (int i = 0; i < HIGHSCORES_MAX; i+=HIGHSCORE_SIZE) {
        char score = highScores[i+4];
        if(score < lowest_score) {
            lowest_index = i;
        }
    }

    if(lowest_index != -1) {
        for (int i = 0; i < HIGHSCORE_SIZE; i++) {
            char address = HIGHSCORES_ADDR + lowest_index + i;
            writeEEprom(address, (i < HIGHSCORE_SIZE) ? name[i] : new_score);
        }
    }
}

void resetHighscores() {
    for (int i = 0; i < HIGHSCORES_MAX; i++) {
        writeEEprom(HIGHSCORES_ADDR+i, 0x0);
    }
}

void getHighscores() {
    char* highScores = readEEpromBytes(HIGHSCORES_ADDR, HIGHSCORES_MAX);
    for (int i = 0; i < HIGHSCORES_MAX; i+=HIGHSCORE_SIZE){
        for(int j = 0; j < 3; j++) {
            print(j, itoaconv(highScores[i+j]));
        }
        print(3, itoaconv(i));
        /* char* name; */
        /* for(int j = 0; j < 4; j++) { */
        /*     *name = highScores[i+j]; */
        /*     name++; */
        /* } */
        /* *name = "\0"; */
        /* print(0, name); */
        /* print(1, itoaconv(highScores[i+4])); */
        delay(1000);
    }
}
